### ISSUE TITLE
When a post contains images, they appear cut off in Ivory

### ISSUE THREAD

**Issue by EshuMarneedi** [videah/SkyBridge#15] opened 2023-05-26 23:44 UTC
This is a pretty interesting bug that I can't tell if is Ivory's fault or not. Tapping on the image reveals the full thing, but when it's in the timeline, it appears cut off. This doesn't happen when using "real" Mastodon instances in Ivory. 

![image](https://github.com/videah/SkyBridge/assets/117054202/66baa700-dd77-4f33-9669-caf4e1992065)

**Comment by videah** [comment] 2023-05-30 18:57
The problem is Bluesky's API does not return any size/aspect ratio information about images in a post, to get this info SkyBridge would either have to download the entire image (which isn't great for performance/bandwidth) or reading just enough bytes to get the image dimensions. The issue with the latter is there are no Dart libraries that do this yet. I want to get this fixed but I have to consider this blocked for now.

**Comment by Treeki** [comment] 2023-06-25 10:38
The lack of metadata also causes Ivory for Mac to crash when you click on an image from the post view (but _not_ from the timeline view).

This is the commit that fixed it in BirdBridge, for reference: https://github.com/Treeki/BirdBridge/commit/4581ae3aed671a80079643022a078b093ee099e6

**Comment by videah** [comment] 2023-08-04 23:38
This has the potential to be fixed if/when [this RFC](https://github.com/bluesky-social/atproto/pull/1306) is merged.

**Comment by videah** [comment] 2023-11-01 16:36
With bluesky now letting clients label image width and size this is now supported for images that do so, most images should render properly without getting cut off as of bde04e4!

**Closed by videah** 2023-11-01 16:36 UTC
Labels: bug
